// <auto-generated />
namespace LTQLSinhVien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_table_GiangVien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_table_GiangVien));
        
        string IMigrationMetadata.Id
        {
            get { return "202012171652528_update_table_GiangVien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
